### ISSUE TITLE
Jakarta EE Specifications page 

### ISSUE THREAD

**Issue by rstjames** [eclipse/microprofile-marketing#940]
Please go to this doc and fill in the needed information to create each page.

https://docs.google.com/document/d/1YOUppCqARpBcmgPvUhwfm-z8JPlvTqAisYVBJJ9xfD4/edit#heading=h.4kitmexapqcp

**Comment by aeiras** [comment]
for this one, we ought to link directly to the Jakarta EE website page. If the page exists there, there is no need to create a new.

**Comment by rstjames** [comment]
@Emily-Jiang I created git tickets for each specification; please check if I didn't miss something. Also, I created a doc that can be used for organizing each spec content. 

https://docs.google.com/document/d/1i2I8zwvoVYx3Dx_d2hXqHwmqv-cVCFxNobWOOhpVhAo/edit?usp=sharing 

Can you please read over this and let me know what you think? 
@aeiras you too :)

**Comment by Emily-Jiang** [comment]
We also need the team to provide a link to the Spec Release Issue under [here](https://github.com/microprofile/microprofile-wg) so that we can find all of the links on the right hand side to the pdf/tck/api jars.
For the Plan Review and Release Review, we can find the ballot info from [here](https://github.com/microprofile/microprofile-wg). I think the good news is that we don't need the spec team to do much but to create an issue here to point to the Release Review issue and we can take all of the info from that issue.
The Intro can be taken from the release history of that spec.

**Comment by Emily-Jiang** [comment]
As for the compatible charts, we need to create/maintain ourselves.

**Comment by rstjames** [comment]
https://docs.google.com/document/d/1i2I8zwvoVYx3Dx_d2hXqHwmqv-cVCFxNobWOOhpVhAo/edit#heading=h.olvqz7p1ihcn

Specification content template

**Comment by Emily-Jiang** [comment]
https://jakarta.ee/specifications/coreprofile/10/
has this.

**Comment by Emily-Jiang** [comment]
@rstjames [here](https://jakarta.ee/specifications/activation/) is a similar page to list the version of the specs, which is the overall page for each individual specs. There is a dedicated page for each released version, e.g. [this](https://jakarta.ee/specifications/activation/2.1/) one.
