### ISSUE TITLE
[Blog Contribution] MicroProfile Booth Experience at DevNexus 2024 

### ISSUE THREAD

**Issue by emecas** [eclipse/microprofile-marketing#971]
**Social Media Description**
 - [ ] Had a great time at the @MicroProfileIO booth at @DevNexus 2024! Learned a lot about our community, developer productivity, software architecture, and the future of Java. #DevNexus #MicroProfile

 **Design Card**  (for MicroProfile designer)
 - [ ]  Minimal requirements highlight the MicroProfiler & the title of the blog

 **Notes**

I am still deciding what image to use  the “Page Header Image”, any suggestion ?

**Comment by rstjames** [comment]
Do we have any pictures of the booth or event? @emecas

**Comment by aeiras** [comment]
@emecas, 

Thank you for making me a part of the review of your DevNexus blog, so fun!  Thank you for choosing to share and add tracing to your travels. 

--

@rstjames there are plenty of pictures in the blog. However I recommend social media blog pic uses the card created for the DevNexus sessions or similar so that DevNexus is highlighted alonge MP logos.

**Comment by rstjames** [comment]
@aeiras There are no pictures in the blog in the MP blog post. The blog post that it links to, most are linked to tweets, and one image that I do not know what copy writes are behind this image.

**Comment by rstjames** [comment]
![mp_devnexus-top](https://github.com/user-attachments/assets/ee4aa1ed-0133-48ac-a1f1-a96046d19ed7)
![microprofile_devnexus_2024_emerson](https://github.com/user-attachments/assets/90a8cd2c-bf9f-4469-ba91-1b3b0993193b)
@emecas

**Comment by rstjames** [comment]
Scheduled
